import type { BankInfo } from '../types/entities';

export const BANKS: BankInfo[] = [
	{ name: 'Ngân hàng TMCP Tiên Phong', code: 'TPB', bin: '970423', shortname: 'TPBank' },
	{
		name: 'Ngân hàng TMCP Phát Triển Thành Phố Hồ Chí Minh',
		code: 'HDB',
		bin: '970437',
		shortname: 'HDBank',
	},
	{
		name: 'Ngân hàng TM TNHH MTV Dầu Khí Toàn Cầu',
		code: 'GPB',
		bin: '970408',
		shortname: 'GPBank',
	},
	{
		name: 'Ngân hàng TMCP Kỹ Thương Việt Nam',
		code: 'TCB',
		bin: '970407',
		shortname: 'Techcombank',
	},
	{
		name: 'Ngân hàng TNHH MTV Hongleong Việt Nam',
		code: 'HLB',
		bin: '970442',
		shortname: 'Hong Leong Bank',
	},
	{ name: 'Ngân hàng TMCP Đại Dương', code: 'OJB', bin: '970414', shortname: 'OceanBank' },
	{ name: 'Ngân hàng TMCP Bảo Việt', code: 'BVB', bin: '970438', shortname: 'BaoViet Bank' },
	{ name: 'Ngân hàng TMCP Quân Đội', code: 'MB', bin: '970422', shortname: 'MB Bank' },
	{ name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng', code: 'VPB', bin: '970432', shortname: 'VPBank' },
	{
		name: 'Ngân hàng TNHH MTV Public Việt Nam',
		code: 'PBVN',
		bin: '970439',
		shortname: 'Public Bank',
	},
	{
		name: 'Ngân hàng TMCP Công Thương Việt Nam',
		code: 'CTG',
		bin: '970415',
		shortname: 'VietinBank',
	},
	{
		name: 'Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam',
		code: 'EIB',
		bin: '970431',
		shortname: 'Eximbank',
	},
	{ name: 'Ngân hàng TMCP Đông Nam Á', code: 'SEAB', bin: '970440', shortname: 'SeABank' },
	{ name: 'Ngân hàng TMCP Sài Gòn', code: 'SCB', bin: '970429', shortname: 'SCB' },
	{ name: 'Ngân hàng TMCP Phương Đông', code: 'OCB', bin: '970448', shortname: 'OCB' },
	{ name: 'Ngân hàng TMCP An Bình', code: 'ABB', bin: '970425', shortname: 'ABBank' },
	{ name: 'Ngân hàng TMCP Hàng Hải Việt Nam', code: 'MSB', bin: '970426', shortname: 'MSB' },
	{ name: 'Ngân hàng TMCP Việt Á', code: 'VAB', bin: '970427', shortname: 'VietABank' },
	{ name: 'Ngân hàng TMCP Quốc Dân', code: 'NCB', bin: '970419', shortname: 'NCB' },
	{
		name: 'Ngân hàng TMCP Đầu Tư và Phát Triển Việt Nam',
		code: 'BIDV',
		bin: '970418',
		shortname: 'BIDV',
	},
	{ name: 'Ngân hàng TMCP Sài Gòn - Hà Nội', code: 'SHB', bin: '970443', shortname: 'SHB' },
	{ name: 'Ngân hàng TMCP Đông Á', code: 'DongABank', bin: '970406', shortname: 'DongA Bank' },
	{ name: 'Ngân hàng TMCP Quốc Tế', code: 'VIB', bin: '970441', shortname: 'VIB' },
	{
		name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
		code: 'SHBVN',
		bin: '970424',
		shortname: 'Shinhan Bank',
	},
	{
		name: 'Ngân hàng TMCP Việt Nam Thương Tín',
		code: 'VIETBANK',
		bin: '970433',
		shortname: 'VietBank',
	},
	{ name: 'Ngân hàng TMCP Bản Việt', code: 'VCCB', bin: '970454', shortname: 'VietCapital Bank' },
	{ name: 'Ngân hàng TMCP Kiên Long', code: 'KLB', bin: '970452', shortname: 'Kienlongbank' },
	{ name: 'Ngân hàng TMCP Xăng Dầu Petrolimex', code: 'PGB', bin: '970430', shortname: 'PG Bank' },
	{
		name: 'Ngân hàng TMCP Sài Gòn Công Thương',
		code: 'SGB',
		bin: '970400',
		shortname: 'SaigonBank',
	},
	{
		name: 'Ngân hàng Nông Nghiệp và Phát Triển Nông Thôn Việt Nam',
		code: 'AGRIBANK',
		bin: '970405',
		shortname: 'Agribank',
	},
	{ name: 'Ngân hàng TMCP Sài Gòn Thương Tín', code: 'STB', bin: '970403', shortname: 'Sacombank' },
	{
		name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
		code: 'PVcombank',
		bin: '970412',
		shortname: 'PVcomBank',
	},
	{ name: 'Ngân hàng Liên Doanh Việt Nga', code: 'VRB', bin: '970421', shortname: 'VRB' },
	{ name: 'Ngân hàng TMCP Nam Á', code: 'NAMABANK', bin: '970428', shortname: 'Nam A Bank' },
	{ name: 'Ngân hàng TNHH Indovina', code: 'IVB', bin: '970434', shortname: 'Indovina Bank' },
	{
		name: 'Ngân hàng TMCP Bưu Điện Liên Việt',
		code: 'LVB',
		bin: '970449',
		shortname: 'LienVietPostBank',
	},
	{ name: 'Ngân hàng Woori Việt Nam', code: 'WOO', bin: '970457', shortname: 'Woori Bank' },
	{
		name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
		code: 'VCB',
		bin: '970436',
		shortname: 'Vietcombank',
	},
	{ name: 'Ngân hàng IBK - Chi nhánh Hà Nội', code: 'IBK', bin: '970455', shortname: 'IBK Hanoi' },
	{ name: 'Ngân hàng TMCP Á Châu', code: 'ACB', bin: '970416', shortname: 'ACB' },
	{ name: 'Ngân hàng TMCP MTV CIMB', code: 'CIMB', bin: '422589', shortname: 'CIMB' },
	{
		name: 'Ngân hàng IBK - Chi nhánh Hồ Chí Minh',
		code: 'IBK',
		bin: '970456',
		shortname: 'IBK HCM',
	},
	{ name: 'Ngân hàng TMCP Bắc Á', code: 'BAB', bin: '970409', shortname: 'Bac A Bank' },
	{ name: 'Ngân hàng TNHH MTV United Overseas Bank', code: 'UOB', bin: '970458', shortname: 'UOB' },
	{
		name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank',
		code: 'CAKE',
		bin: '546034',
		shortname: 'CAKE',
	},
	{ name: 'NONGHYUP - Chi nhánh Hà Nội', code: 'NHB', bin: '801011', shortname: 'NongHyup' },
	{ name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)', code: 'HSBC', bin: '458761', shortname: 'HSBC' },
	{
		name: 'Ngân hàng TMCP MTV Xây Dựng Việt Nam',
		code: 'CBB',
		bin: '970444',
		shortname: 'CB Bank',
	},
	{
		name: 'Ngân hàng TNHH MTV Standard Chartered Bank (Vietnam) Limited',
		code: 'SCVN',
		bin: '970410',
		shortname: 'Standard Chartered',
	},
	{
		name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank',
		code: 'UBANK',
		bin: '546035',
		shortname: 'UBank',
	},
	{ name: 'DBS - Ho Chi Minh Branch', code: 'DBS', bin: '796500', shortname: 'DBS' },
	{
		name: 'Đại chúng TNHH Kasikornbank - Chi nhánh TP. HCM',
		code: 'KBANK',
		bin: '668888',
		shortname: 'KBank',
	},
	{
		name: 'Ngân hàng TMCP Kiên Long - Ngân hàng số UMEE by Kienlongbank',
		code: 'UMEE',
		bin: '963399',
		shortname: 'UMEE',
	},
	{ name: 'Ngân hàng Chính sách Xã hội', code: 'VBSP', bin: '999888', shortname: 'VBSP' },
];
